/**
 * Created by xxnr-cd on 16/7/12.
 */
/**
 * Created by xxnr-cd on 16/7/12.
 */
module.exports = {
    logonSelectors: {
        flashMessage:'html.ng-scope body.ng-scope flash-message.ng-isolate-scope  span span.ng-scope',
        PopContent:'.pop_content',

        headerRegisterBtn:'a#header_register span',
        logonRegisterForm:'div.register_form',
        logonRegisterFormTitle:'div.register_form p.register_form--title',
        logonLoginForm:'div.login_form',
        logonLoginFormRegisterBtn:'div.login_form form.ng-pristine.ng-invalid.ng-invalid-required div.register_message.clearfix span.right a',
        logonLoginFormPhone:'div.login_form .form-group:nth-child(1) input',
        logonLoginFormPassword:'div.login_form .form-group:nth-child(2) input',
        logonLoginFormLoginBtn:'.login_btn',
        logonRegisterFormLoginLinkBtn:'.login_link a',
        logonRegisterFormRegisterBtn:'button.register_btn',
        logonRegisterFormErrMessage:'div.register_error span.ng-binding',
        logonLoginFormErrMessage:'div.login_error span',
        logonRegisterFormPhoneInput:'div.register_form form.registerForm div.form-group:first-child input',
        logonRegisterFormGetCodeBtn:'div.right.reg_get_code_btn a.ng-binding',
        logonRegisterFormVerificationCode:'.verification-code',
        logonRegisterFormGraphVerificationCodeInput:'.verification-code-input',
        logonRegisterFormVerificationCodeInput:'.register_code input',
        logonRegisterFormGraphCaptchaImg:'.captcha_graph > img',
        logonRegisterFormPassword:'.register_password input',
        logonRegisterFormConfirmPassword:'.register_confirm_password input',
        policy:'.pop_content_policy',
        policyCheck:'.policy input',
        headerLogin:'#header_login',
        headerWelcomeLinkWithUserName:'.login a:nth-child(1)',
        banner:".banner",
        keepLogin:'.keepLogin',
        profileFillingForm:'.profile_box',

        forgetPassword : '.forgetPassword',
        forgetPasswordPop :'.pop_content',
        forgetPasswordPopPhone:'.pop_content .pop_login #tel',
        forgetPasswordPopSMSCode:'.pop_content .pop_login #dynamic_code',
        forgetPasswordPopPassword:'.pop_content .pop_login #pop_password',
        forgetPasswordPopConfirmPassword:'.pop_content .pop_login #pop_password_cf',
        forgetPasswordPopSendSMSCode:'.pop_content .pop_login .reg_get_code',
        forgetPasswordPopCommitBtn:'.pop_content .pop_login .btn',
        forgetPasswordPopErrMsg:'div.reset_password_err span',

        myxxnrNickname: '.nickname',
        myxxnrName: '.name',
        myxxnrAddress: '.userProfile p:nth-child(2)',
        myxxnrType: '.type',
        myxxnrSex: '.sex',
        myxxnrHuizhang:'.huizhang',
        myxxnrModifyInfoBtn:'.modifyInfo',
        myxxnrNicknameHoverEditBtn: '.nickname span',
        myxxnrUserInfoBox: '.jifen_box',
        myxxnrProfileNotFilledBox:'.notFilledTop',
        myxxnrProfileNicknameAddinglink:'.NicknameAddinglink',
        myxxnrProfileFillProfileGetPoint:'.needToFillProfile a',
        myxxnrProfileEditNicknameInput:'.editNickname input',
        myxxnrProfileEditNicknameCommitBtn:'.editNickname a',
        myxxnrProfileUserAvatar:'.user_img img',
        myxxnrProfileOldAvatar:'.oldAvatarImg',
        myxxnrProfileModifyPassword:'.modifyPassword',
        myxxnrProfileModifyPasswordOldPassword:'#password',
        myxxnrProfileModifyPasswordOldNewPassword:'#new_password',
        myxxnrProfileModifyPasswordOldNewPasswordConfirm:'#new_password_cf',
        myxxnrProfileModifyCommitBtn:'.pop_body .pop_login .btn',
        myxxnrProfileModifyErr:'.my_xxnr_password_err',
        myxxnrProfilePoint:'.num',
        myxxnrProfileInvitationBtn:'.invitation_btn a',

        fillProfileBox:'.profile_box',
        fillProfileBoxNoFilledTitle:'.profile_box--title--section span',
        fillProfileName:'#name',
        fillProfileSex:'.sex_form input[type="radio"]:checked',
        fillProfileMale:'div.sex_form input[value="male"]',
        fillProfileFemale:'div.sex_form input.female',
        fillProfileProvince:'#provin option:selected',
        fillProfileCity:'#city option:selected',
        fillProfileCounty:'#county option:selected',
        fillProfileTown:'#town option:selected',
        fillProfileType:'.identity option:selected',
        fillProfileNameValidateError:'.name .validate_error',
        fillProfileCommitBtn:'a.save',
        fillProfileAddressProvinceSelect:'#provin',
        fillProfileAddressCitySelect:'#city',
        fillProfileAddressCountySelect:'#county',
        fillProfileAddressTownSelect:'#town',
        fillProfileSkipFillProfile:'.profile--cancel',

        applyCountyForm:'.applyCountyForm',
        applyCountyFormName:'.applyCountyForm input[name=name]',
        applyCountyFormID:'.applyCountyForm input[name=ID_Num]',
        applyCountyFormShopName:'.applyCountyForm input[name=companyName]',
        applyCountyFormPhoneNum:'.applyCountyForm input[name=phoneNum]',
        applyCountyFormDetailAddress:'.applyCountyForm input[name=detailAddress]',

        pointsRecordingSection:'.pointsRecording_section',
        pointsRecordingSectionPoint:'.pointsRecording_section .my_points span',

        invitationSection:'.invitation_section'
    }
};