/**
 * Created by pepelu on 2016/3/23.
 */
var EPOSConfig = {
    RSAPublicKey :'-----BEGIN PUBLIC KEY-----' + '\r\n' +
    'QkYxRjE2N0Q0MTNBOUY3NzU1MEFEMjVCMkUwMTA1ODA5Njk1RUY0NTk5NUVBREE4' + '\r\n' +
    'Qjk2OTg3MEIwMzU3MkUzNEFCRTE0NjdEMjIyNkM2MUQ3RUNBNEQyOEZGM0U4Q0Yy' + '\r\n' +
    'M0ExNzUzQkY0QjI3NzA4QURBQUY1QjUyMjEwMDE2MkVBRTZBQTRGRjEzNTRGOEND' + '\r\n' +
    'QzJFRjZFNTdGNThEODM1RUFEOUVBNjNGNzk4QTMwNDg1N0IxRjhDOTZCQTgwMDIz' + '\r\n' +
    'RDQ0RjExNkY3NzY3NDZEMzZCQTgyM0YzNjZCRDFCNjQ4QjMxMTQwNzZDODY5RkJC' + '\r\n' +
    'M0EwMzE1QTg3NDNEN0M4QTExREM0OTE4MEMyMjQ1QzMxRjREODNDQkI5OTM4QTlC' + '\r\n' +
    'QjhEMkMwNEExQjVDQjk5NDYwQTBDQjRGMEMyMDc1RTIxQkNCM0ZFN0FFOTdENUJF' + '\r\n' +
    'MjU0MjBBQkZFMDUzMUI2QkZEQjhDODc4RDk5QTc3MzRGNkFDRDZGNzUzMkFEMEMz' + '\r\n' +
    'NUZCMTgwQjIyQkJBN0RFQzc5MjkzRUYzNjMxNUNEM0FCODNDMzU4MUIzMDA4MkYy' + '\r\n' +
    'MTRGM0JDNkMzQTJDMTVDNzdFOTdGNDgzRjhDRjE2NzEzOUFDMzgwRjdDNjIzNUFC' + '\r\n' +
    'MzlDN0E5MDcwMkFCNUE4NUE4N0JCRkYzNDAzNEVGRDEwMDAwMDAwMDAwMDAwMDAw' + '\r\n' +
    'MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw' + '\r\n' +
    'MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw' + '\r\n' +
    'MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw' + '\r\n' +
    'MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw' + '\r\n' +
    'MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw' + '\r\n' +
    'MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw' + '\r\n' +
    'MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw' + '\r\n' +
    'MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw' + '\r\n' +
    'MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw' + '\r\n' +
    'MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw' + '\r\n' +
    'MDAwMDAwMDAwMDAxMDAwMQ==' + '\r\n' +
    '-----END PUBLIC KEY-----',
    DES3Secret : 'f6cbb47b934cb5eb85f1594647e5d017'
};

exports.EPOSConfig = Object.freeze(EPOSConfig);